# Generated by Django 4.2.2 on 2025-01-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alumno",
            fields=[
                (
                    "boleta",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("nombre_completo", models.CharField(max_length=255)),
                ("contraseña", models.CharField(max_length=255)),
                ("edad", models.IntegerField()),
                ("foto_perfil", models.URLField()),
                ("parcial1", models.FloatField()),
                ("parcial2", models.FloatField()),
                ("parcial3", models.FloatField()),
                ("final", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Gestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_completo", models.CharField(max_length=255)),
                ("correo", models.EmailField(max_length=254, unique=True)),
                ("contraseña", models.CharField(max_length=255)),
                ("foto_perfil", models.URLField()),
            ],
        ),
    ]
